# Generated by Django 4.1 on 2022-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok_mc_number',
            name='mcnumber',
            field=models.TextField(blank=50, verbose_name='name'),
        ),
    ]
