# Generated by Django 4.1 on 2022-09-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0003_alter_spisok_mc_number_mcnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok_mc_number',
            name='mcnumber',
            field=models.TextField(blank=50, verbose_name='MC Number'),
        ),
    ]
