# Generated by Django 4.1 on 2022-09-05 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0004_alter_spisok_mc_number_mcnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spisok_mc_number',
            options={'verbose_name': 'List MC Number', 'verbose_name_plural': 'List MC Number'},
        ),
    ]
